#!/bin/sh

NAME="Federico Bruzzone"
EMAIL="federico.bruzzone.i@gmail.com"

SOB="Signed-off-by: $NAME <$EMAIL>"
AB="Assisted-by: GitHub-Copilot:auto"

# Add the "Signed-off-by" and "Assisted-by" lines to the commit message if they are not already present
# The \n ensures there is an empty line before the signature
grep -q "$SOB" "$1" || echo "\n$SOB" >> "$1"
grep -q "$AB" "$1" || echo "$AB" >> "$1"
